#!/usr/bin/env bash
# script modified from https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5
set -e

scope=$1
# format it just in case
alejandra . &>/dev/null ||
    (
        alejandra .
        echo "formatting failed"
        exit 1
    )
echo "Scope: $scope"
if [ "$scope" == "home" ]; then
    echo "Rebuilding Home Manager..."
    home-manager switch --flake ./ --recreate-lock-file &>$HOME/home-rebuild.log || (cat $HOME/home-rebuild.log | grep --color error && exit 1)
    current=$(date +"%d-%m-%Y %r")
    commit_msg="Home Manager rebuilt on $current"
fi
if [ "$scope" == "system" ]; then
    echo "Rebuilding NixOS..."
    sudo nixos-rebuild switch --flake ./ &>$HOME/rebuild.log || (cat $HOME/rebuild.log | grep --color error && exit 1)
    commit_msg=$(nixos-rebuild list-generations | grep current)
fi

git commit -am "$commit_msg"
notify-send -e "NixOS ${scope} rebuilt successfully" --icon=software-update-available
