image: python:3

stages:
  - release

Attach versioned zip to release:
  stage: release
  script:
    - pip3 install gitlab-release
    - mkdir /tmp/eucalyptus-drop
    - mv ./* /tmp/eucalyptus-drop/
    - cd /tmp
    - gitlab-release --zip "sddm-eucalyptus-drop-${CI_COMMIT_TAG}.zip" ./eucalyptus-drop
  only:
    - tags
